### ISSUE TITLE
When you import a direct private key it shouldn't ask you for a passphrase 

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-wallet#48]
context: 
After I Imported my private key and entered a passphrase, it takes me to the main screen as expected. but if I refresh it takes me back to the login screen and I have to repeat the steps. I can even enter a different passphrase.

Is this expected behavior, and why do I need to enter a passphrase when it doesn't even save it?

Solution:
just get rid of the passphrase box.

**Comment by pabelnl** [comment]
When you import a raw private key, the passphrase we ask is to encrypt the passphrase in the pocket keybase instance, allowing us to use this account later on when you want to send a transaction, since we only store the private key in memory when you refresh it is expected to send you back to the home page since no account information is available.

Remember the wallet is a static website with no backend.

**Comment by luyzdeleon** [comment]
This issue can be closed.
